# Input and output paths for ETL and consumption
# All output paths are S3 or local paths (Hudi tables for ETL, CSV for consumption)

seller_catalog:
  # input files
  # ETL output (Hudi)
  input_path: "/opt/spark/work-dir/input_data_sets/clean/seller_catalog_clean.csv" # raw
  hudi_output_path: "/opt/spark/work-dir/data/2025em1100506/processed/seller_catalog_hudi/" # processed

company_sales:
  # input files
  # ETL output (Hudi)
  input_path: "/opt/spark/work-dir/input_data_sets/clean/company_sales_clean.csv" # raw
  hudi_output_path: "/opt/spark/work-dir/data/2025em1100506/processed/company_sales_hudi/" # processed

competitor_sales:
  input_path: "/opt/spark/work-dir/input_data_sets/clean/competitor_sales_clean.csv" # raw
  # input files
  hudi_output_path: "/opt/spark/work-dir/data/2025em1100506/processed/competitor_sales_hudi/" # ETL output (Hudi)

recommendation:
  # Final consumption layer input/output
  seller_catalog_hudi: "/opt/spark/work-dir/data/2025em1100506/processed/seller_catalog_hudi/"
  company_sales_hudi: "/opt/spark/work-dir/data/2025em1100506/processed/company_sales_hudi/"
  competitor_sales_hudi: "/opt/spark/work-dir/data/2025em1100506/processed/competitor_sales_hudi/"
  output_csv: "/opt/spark/work-dir/data/2025em1100506/processed/recommendations_csv/seller_recommend_data.csv" # final CSV

