version: '3.8'

services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    entrypoint: ["/bin/bash", "/opt/spark/work-dir/docker-entrypoint.sh"]
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"   # Spark Master Web UI
      - "7077:7077"   # Spark Master Port
    environment:
      - IVY_HOME=/opt/spark/.ivy2
      - SPARK_HOME=/opt/spark
      - HOME=/opt/spark
    volumes:
      - ./src:/opt/spark/work-dir/src
      - ./configs:/opt/spark/work-dir/configs
      - ./scripts:/opt/spark/work-dir/scripts
      - ./data:/opt/spark/work-dir/data
      - ./quarantine:/opt/spark/work-dir/quarantine
      - ./input_data_sets:/opt/spark/work-dir/input_data_sets
      - ../../../../docker-entrypoint.sh:/opt/spark/work-dir/docker-entrypoint.sh
    networks:
      - spark-network

  spark-worker-1:
    image: apache/spark:3.5.0
    container_name: spark-worker-1
    hostname: spark-worker-1
    entrypoint: ["/bin/bash", "/opt/spark/work-dir/docker-entrypoint.sh"]
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Spark Worker Web UI
    environment:
      - IVY_HOME=/opt/spark/.ivy2
      - SPARK_HOME=/opt/spark
      - HOME=/opt/spark
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - ./src:/opt/spark/work-dir/src
      - ./configs:/opt/spark/work-dir/configs
      - ./scripts:/opt/spark/work-dir/scripts
      - ./data:/opt/spark/work-dir/data
      - ./quarantine:/opt/spark/work-dir/quarantine
      - ./input_data_sets:/opt/spark/work-dir/input_data_sets
      - ../../../../docker-entrypoint.sh:/opt/spark/work-dir/docker-entrypoint.sh
    networks:
      - spark-network

  spark-worker-2:
    image: apache/spark:3.5.0
    container_name: spark-worker-2
    hostname: spark-worker-2
    entrypoint: ["/bin/bash", "/opt/spark/work-dir/docker-entrypoint.sh"]
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8081"   # Spark Worker Web UI
    environment:
      - IVY_HOME=/opt/spark/.ivy2
      - SPARK_HOME=/opt/spark
      - HOME=/opt/spark
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - ./src:/opt/spark/work-dir/src
      - ./configs:/opt/spark/work-dir/configs
      - ./scripts:/opt/spark/work-dir/scripts
      - ./data:/opt/spark/work-dir/data
      - ./quarantine:/opt/spark/work-dir/quarantine
      - ./input_data_sets:/opt/spark/work-dir/input_data_sets
      - ../../../../docker-entrypoint.sh:/opt/spark/work-dir/docker-entrypoint.sh
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

